// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'Models/tasbih_model.dart';


export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 9147271546381087750),
      name: 'TasbihModel',
      lastPropertyId: const IdUid(3, 2343131469187212872),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5907327878159604143),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6103613727049041265),
            name: 'virdh',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 2343131469187212872),
            name: 'count',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 9147271546381087750),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    TasbihModel: EntityDefinition<TasbihModel>(
        model: _entities[0],
        toOneRelations: (TasbihModel object) => [],
        toManyRelations: (TasbihModel object) => {},
        getId: (TasbihModel object) => object.id,
        setId: (TasbihModel object, int id) {
          object.id = id;
        },
        objectToFB: (TasbihModel object, fb.Builder fbb) {
          final virdhOffset =
              object.virdh == null ? null : fbb.writeString(object.virdh!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, virdhOffset);
          fbb.addInt64(2, object.count);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TasbihModel(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              virdh: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              count: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [TasbihModel] entity fields to define ObjectBox queries.
class TasbihModel_ {
  /// see [TasbihModel.id]
  static final id =
      QueryIntegerProperty<TasbihModel>(_entities[0].properties[0]);

  /// see [TasbihModel.virdh]
  static final virdh =
      QueryStringProperty<TasbihModel>(_entities[0].properties[1]);

  /// see [TasbihModel.count]
  static final count =
      QueryIntegerProperty<TasbihModel>(_entities[0].properties[2]);
}
